---
title: "DataAnalyze"
author: "Gabi Smith-Rosario and Andrea Boskovic"
date: "4/15/2018"
output: html_document
---

```{r, include=FALSE}
require(mosaic);require(leaps); require(car); require(MASS)
```

```{r}
<<<<<<< HEAD
summary(RodentsP)
```

```{r}
#CHECK for multicollinearity.. do this
#throw in the kitchen sink
#not working??
fmfull <- lm(MaxLongevitym~.,data=RodentsP)
=======
#CHECK for multicollinearity
fmfull<-lm(MaxLongevitym ~ ActivityCycle + AdultBodyMassg + AdultHeadBodyLenmm + AgeatEyeOpeningd + BasalMetRatemLOhr + BasalMetRateMassg + DietBreadth + GestationLend + HabitatBreadth + LitterSize + LittersPerYear + PopulationDensitynkm + PopulationGrpSize + SexualMaturityAged + TeatNumber + Terrestriality + TrophicLevel + WeaningAged + HuPopDenMinnkm + HuPopDenMeannkm + HuPopDenpnkm + HuPopDenChange + PrecipMeanmm + TempMeandegC + AETMeanmm + PETMeanmm,data=RodentsP)
>>>>>>> 5a222f2dbb766f3c6a7de3beb5b591cdbc3b306d
summary(fmfull)
vif(fmfull)
```

```{r}
<<<<<<< HEAD
RodentsP <- RodentsP[-c(1752), ] #is it worth taking this out.. normality condition gets really bad
mod1 <- lm(MaxLongevitym~BasalMetRatemLOhr*GestationLend+AgeatEyeOpeningd, data = RodentsP)
=======
mod1se <- lm(MaxLongevitym~BasalMetRatemLOhr*GestationLend*AgeatEyeOpeningd, data = RodentsP)
>>>>>>> 5a222f2dbb766f3c6a7de3beb5b591cdbc3b306d
plot(mod1,which=1)
plot(mod1,which=2)
summary(mod1)
anova(mod1)
vif(mod1) #big vif??? what now
```

```{r}
xyplot(MaxLongevitym ~ BasalMetRatemLOhr, type=c("p","r"),data=RodentsP)
#remove outlier and try again
which(RodentsP$BasalMetRatemLOhr> 6000)
RodentsP <- RodentsP[-c(627), ]
xyplot(MaxLongevitym ~ BasalMetRatemLOhr, type=c("p","r"),data=RodentsP)
```

```{r}
xyplot(MaxLongevitym ~ GestationLend, type=c("p","r"), data=RodentsP)
```

```{r}
xyplot(MaxLongevitym ~ AgeatEyeOpeningd, type=c("p","r"), data=RodentsP)
#make an added variable plot bc negative slope here but variable has positive slope coef in model with other predictors
fm1 <- lm(MaxLongevitym~BasalMetRatemLOhr*GestationLend, data = RodentsP)
fm2 <- lm(AgeatEyeOpeningd ~ BasalMetRatemLOhr*GestationLend, data=RodentsP)
plotPoints(fm1$residuals ~ fm2$residuals, type=c("p", "r"), pch=19, alpha=0.3, cex=2, main="Added Variable Plot for AgeatEyeOpeningd")
#not working because of different variable lengths?... plot models against each other?
fm3 <- lm(fm1$residuals ~ fm2$residuals)
```

identifying unusual/influential pts
```{r}
plot(mod1,which=3)
plot(mod1,which=4)
plot(mod1,which=5)
plot(mod1,which=6)
```
problematic pts in model seem to be 162, 256, 272

```{r}
RodentsP <- RodentsP[-c(162), ]
RodentsP <- RodentsP[-c(256), ]
RodentsP <- RodentsP[-c(272), ]
plot(mod1, which=1)
plot(mod1, which=2)
```

```{r}
RodentsP <- mutate(RodentsP, MaxLongevitym.new=log(MaxLongevitym))
mod2 <- lm(MaxLongevitym~BasalMetRatemLOhr*GestationLend+AgeatEyeOpeningd, data = RodentsP)
plot(mod2, which=1)
plot(mod2, which=2)
#log is bad, let's try sqrt
RodentsP <- mutate(RodentsP, MaxLongevitym.new2=sqrt(MaxLongevitym))
mod3 <- lm(MaxLongevitym~BasalMetRatemLOhr*GestationLend+AgeatEyeOpeningd, data = RodentsP)
plot(mod3, which=1)
plot(mod3, which=2)
#this didn't help
```

```{r}
modsmall<-lm(MaxLongevitym~1,data=RodentsP)
fmfull <- lm(MaxLongevitym ~ BasalMetRatemLOhr + GestationLend + AgeatEyeOpeningd + AdultBodyMassg + LitterSize + LittersPerYear + HuPopDenpnkm, data = RodentsP)
#stepAIC(modsmall,scope=list(upper=fmfull, lower=~1), direction="both",trace=FALSE)$anova
```


```{r}
confint(mod1)
```

```{r bootstrap}
#Check if we really need BasalMetRatemLOhr in the model
set.seed(293)
bootstrap <- do(1000) * lm(MaxLongevitym~BasalMetRatemLOhr*GestationLend + AgeatEyeOpeningd, data=rodents2[mosaic::resample(1:nrow(rodents2)),])$coefficients
densityplot(~BasalMetRatemLOhr, data=bootstrap)
ladd(panel.abline(v=mod1$coefficients["BasalMetRatemLOhr"], col="red", lwd=3))
```
